name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pipeline will run when you push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu VM to run the pipeline

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: 3.9  # Specify the version of Python you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run unit tests
        run: |
          pytest  # Run unit tests using pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Run this job only if the build job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          echo "Deployment step"  # Placeholder for the deployment script
